### ISSUE TITLE
Is there a way to find the package extension?

### ISSUE THREAD

**Issue by NextDev65** [StoreDev/StoreLib#10]
For example is it .appx, .eappx, .appxbundle, or .eappxbundle?

**Comment by tuxuser** [comment]
Here is some code that achieved that, unsure if it still works though.

https://github.com/StoreDev/StoreBot/commit/c3bb9c04311b34d9bfd32474e6bc783b206dc1a7

**Comment by NextDev65** [comment]
Huh. I was using the heroku hosted site and dl's had no file extension. Maybe it hasn't been implemented yet.
